BEGIN;

ALTER TABLE activity ADD COLUMN IF NOT EXISTS event_time VARCHAR(50);
ALTER TABLE activity ADD COLUMN IF NOT EXISTS start_time TIME;
ALTER TABLE activity ADD COLUMN IF NOT EXISTS end_time TIME;

COMMIT;
